import { IProductInput } from '@/types';
import { toSlug } from './utils';

// Using the vendorId from the provided sample
const vendorId = '680f6385dda6cc18bb5a62ec';

// Helper function to generate a unique ObjectId-like string
const generateObjectId = () => {
  const timestamp = Math.floor(new Date().getTime() / 1000).toString(16);
  const machineId = Math.floor(Math.random() * 16777216).toString(16).padStart(6, '0');
  const processId = Math.floor(Math.random() * 65536).toString(16).padStart(4, '0');
  const counter = Math.floor(Math.random() * 16777216).toString(16).padStart(6, '0');
  return timestamp + machineId + processId + counter;
};

// Define a type that includes the fields we use in mock data
type MockProduct = {
  _id: string;
  name: string;
  slug: string;
  category: string;
  images: string[];
  brand: string;
  description: string;
  price: number;
  listPrice: number;
  stock: number;
  vendorId: string;
  status: string;
  isActive: boolean;
  tags: string[];
  colors: string[];
  sizes: string[];
  avgRating: number;
  numReviews: number;
  ratingDistribution: any[];
  numSales: number;
  isPublished: boolean;
  reviews: any[];
  createdAt: Date;
  updatedAt: Date;
};

// 20 mockup products with different categories
export const mockupProducts: MockProduct[] = [
  {
    _id: generateObjectId(),
    name: 'Premium Wireless Headphones',
    slug: 'premium-wireless-headphones',
    category: 'Electronics',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'SoundMaster',
    description: 'Premium wireless headphones with noise cancellation and 30-hour battery life.',
    price: 199.99,
    listPrice: 249.99,
    stock: 50,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['featured', 'best-seller', 'new-arrival'],
    colors: ['Black', 'White', 'Blue'],
    sizes: ['One Size'],
    avgRating: 4.8,
    numReviews: 124,
    ratingDistribution: [],
    numSales: 85,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Slim Fit T-Shirt',
    slug: 'slim-fit-t-shirt',
    category: 'Clothing',
    images: [
      'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'FashionLite',
    description: 'Comfortable slim fit t-shirt made from 100% organic cotton.',
    price: 24.99,
    listPrice: 29.99,
    stock: 200,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['best-seller', 'todays-deal'],
    colors: ['White', 'Black', 'Navy', 'Red'],
    sizes: ['S', 'M', 'L', 'XL'],
    avgRating: 4.5,
    numReviews: 78,
    ratingDistribution: [],
    numSales: 120,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Ergonomic Office Chair',
    slug: 'ergonomic-office-chair',
    category: 'Furniture',
    images: [
      'https://images.unsplash.com/photo-1505843490701-5be5d1b31f8f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'ComfortPro',
    description: 'Ergonomic office chair with lumbar support and adjustable height.',
    price: 149.99,
    listPrice: 179.99,
    stock: 35,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['featured', 'new-arrival'],
    colors: ['Black', 'Gray'],
    sizes: ['One Size'],
    avgRating: 4.7,
    numReviews: 45,
    ratingDistribution: [],
    numSales: 30,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Smart Fitness Watch',
    slug: 'smart-fitness-watch',
    category: 'Electronics',
    images: [
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'TechFit',
    description: 'Smart fitness watch with heart rate monitor, GPS, and 7-day battery life.',
    price: 129.99,
    listPrice: 149.99,
    stock: 75,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['best-seller', 'todays-deal', 'new-arrival'],
    colors: ['Black', 'Silver', 'Rose Gold'],
    sizes: ['One Size'],
    avgRating: 4.6,
    numReviews: 92,
    ratingDistribution: [],
    numSales: 68,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Professional Chef Knife Set',
    slug: 'professional-chef-knife-set',
    category: 'Kitchen',
    images: [
      'https://images.unsplash.com/photo-1593618998160-854549d09c43?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1566454419290-57a0589c9d46?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'KitchenPro',
    description: 'Professional 8-piece chef knife set with German stainless steel blades.',
    price: 89.99,
    listPrice: 119.99,
    stock: 40,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['featured', 'todays-deal'],
    colors: ['Silver'],
    sizes: ['One Size'],
    avgRating: 4.9,
    numReviews: 56,
    ratingDistribution: [],
    numSales: 42,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Ultra HD 4K Smart TV',
    slug: 'ultra-hd-4k-smart-tv',
    category: 'Electronics',
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1588508065123-287b28e013da?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'VisualTech',
    description: '55-inch Ultra HD 4K Smart TV with built-in streaming apps and voice control.',
    price: 499.99,
    listPrice: 599.99,
    stock: 25,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['featured', 'best-seller'],
    colors: ['Black'],
    sizes: ['55"', '65"'],
    avgRating: 4.7,
    numReviews: 83,
    ratingDistribution: [],
    numSales: 38,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Leather Wallet for Men',
    slug: 'leather-wallet-for-men',
    category: 'Accessories',
    images: [
      'https://images.unsplash.com/photo-1614330316655-81ad9c494b4f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1589782182778-b5c5e6c25104?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'LeatherCraft',
    description: 'Genuine leather wallet for men with RFID blocking technology.',
    price: 39.99,
    listPrice: 49.99,
    stock: 100,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['best-seller', 'todays-deal'],
    colors: ['Brown', 'Black'],
    sizes: ['One Size'],
    avgRating: 4.4,
    numReviews: 37,
    ratingDistribution: [],
    numSales: 65,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Outdoor Camping Tent',
    slug: 'outdoor-camping-tent',
    category: 'Sports & Outdoors',
    images: [
      'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'AdventureGear',
    description: 'Waterproof 4-person camping tent with easy setup and storage bag.',
    price: 129.99,
    listPrice: 159.99,
    stock: 30,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['new-arrival', 'featured'],
    colors: ['Green', 'Blue'],
    sizes: ['4-Person', '6-Person'],
    avgRating: 4.3,
    numReviews: 28,
    ratingDistribution: [],
    numSales: 22,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Wireless Bluetooth Speaker',
    slug: 'wireless-bluetooth-speaker',
    category: 'Electronics',
    images: [
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1589003077984-894e133dabab?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'SoundWave',
    description: 'Portable wireless Bluetooth speaker with 20-hour battery life and waterproof design.',
    price: 79.99,
    listPrice: 99.99,
    stock: 60,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['best-seller', 'todays-deal'],
    colors: ['Black', 'Blue', 'Red'],
    sizes: ['One Size'],
    avgRating: 4.6,
    numReviews: 74,
    ratingDistribution: [],
    numSales: 58,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Organic Skin Care Set',
    slug: 'organic-skin-care-set',
    category: 'Beauty',
    images: [
      'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'NaturalGlow',
    description: 'Complete organic skin care set with cleanser, toner, and moisturizer.',
    price: 69.99,
    listPrice: 89.99,
    stock: 45,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['featured', 'new-arrival'],
    colors: [''],
    sizes: ['One Size'],
    avgRating: 4.8,
    numReviews: 42,
    ratingDistribution: [],
    numSales: 31,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Stainless Steel Water Bottle',
    slug: 'stainless-steel-water-bottle',
    category: 'Kitchen',
    images: [
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1610824352934-c10d87b700cc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'EcoLife',
    description: 'Double-wall insulated stainless steel water bottle, keeps drinks cold for 24 hours and hot for 12 hours.',
    price: 34.99,
    listPrice: 39.99,
    stock: 120,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['best-seller', 'todays-deal'],
    colors: ['Silver', 'Black', 'Blue', 'Red'],
    sizes: ['500ml', '750ml', '1L'],
    avgRating: 4.7,
    numReviews: 89,
    ratingDistribution: [],
    numSales: 76,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Yoga Mat with Carrying Strap',
    slug: 'yoga-mat-with-carrying-strap',
    category: 'Sports & Outdoors',
    images: [
      'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'ZenFit',
    description: 'Non-slip yoga mat with carrying strap, eco-friendly TPE material, 6mm thickness.',
    price: 29.99,
    listPrice: 39.99,
    stock: 80,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['new-arrival', 'featured'],
    colors: ['Purple', 'Blue', 'Black', 'Pink'],
    sizes: ['One Size'],
    avgRating: 4.5,
    numReviews: 36,
    ratingDistribution: [],
    numSales: 29,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Professional DSLR Camera',
    slug: 'professional-dslr-camera',
    category: 'Electronics',
    images: [
      'https://images.unsplash.com/photo-1516724562728-afc824a36e84?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'PhotoPro',
    description: 'Professional DSLR camera with 24.2MP sensor, 4K video recording, and Wi-Fi connectivity.',
    price: 899.99,
    listPrice: 999.99,
    stock: 15,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['featured', 'best-seller'],
    colors: ['Black'],
    sizes: ['One Size'],
    avgRating: 4.9,
    numReviews: 47,
    ratingDistribution: [],
    numSales: 18,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Gaming Laptop',
    slug: 'gaming-laptop',
    category: 'Computers',
    images: [
      'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'TechGear',
    description: 'High-performance gaming laptop with RTX 3070 GPU, 16GB RAM, 1TB SSD, and 15.6" 144Hz display.',
    price: 1299.99,
    listPrice: 1499.99,
    stock: 10,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['featured', 'new-arrival'],
    colors: ['Black'],
    sizes: ['15.6"', '17.3"'],
    avgRating: 4.8,
    numReviews: 25,
    ratingDistribution: [],
    numSales: 12,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Stylish Sunglasses',
    slug: 'stylish-sunglasses',
    category: 'Accessories',
    images: [
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'ShadeStyle',
    description: 'Stylish polarized sunglasses with UV protection and lightweight frame.',
    price: 59.99,
    listPrice: 79.99,
    stock: 70,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['best-seller', 'todays-deal'],
    colors: ['Black', 'Brown', 'Blue'],
    sizes: ['One Size'],
    avgRating: 4.4,
    numReviews: 33,
    ratingDistribution: [],
    numSales: 52,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Compact Air Purifier',
    slug: 'compact-air-purifier',
    category: 'Home',
    images: [
      'https://images.unsplash.com/photo-1595393550859-bb05f720b615?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1585412913311-9db419132660?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'PureAir',
    description: 'Compact air purifier with HEPA filter, perfect for bedrooms and offices up to 200 sq ft.',
    price: 119.99,
    listPrice: 149.99,
    stock: 25,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['new-arrival', 'featured'],
    colors: ['White'],
    sizes: ['One Size'],
    avgRating: 4.6,
    numReviews: 29,
    ratingDistribution: [],
    numSales: 21,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Mechanical Keyboard',
    slug: 'mechanical-keyboard',
    category: 'Computers',
    images: [
      'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'KeyMaster',
    description: 'RGB mechanical keyboard with customizable switches and programmable keys.',
    price: 89.99,
    listPrice: 109.99,
    stock: 40,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['best-seller', 'featured'],
    colors: ['Black', 'White'],
    sizes: ['One Size'],
    avgRating: 4.7,
    numReviews: 48,
    ratingDistribution: [],
    numSales: 36,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Ceramic Coffee Mug Set',
    slug: 'ceramic-coffee-mug-set',
    category: 'Kitchen',
    images: [
      'https://images.unsplash.com/photo-1533090368676-1fd25485db01?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1564466809058-bf4114d55352?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'HomeStyle',
    description: 'Set of 4 ceramic coffee mugs, microwave and dishwasher safe.',
    price: 29.99,
    listPrice: 39.99,
    stock: 60,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['todays-deal', 'new-arrival'],
    colors: ['White', 'Black', 'Blue', 'Mixed'],
    sizes: ['One Size'],
    avgRating: 4.5,
    numReviews: 54,
    ratingDistribution: [],
    numSales: 47,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: generateObjectId(),
    name: 'Travel Backpack',
    slug: 'travel-backpack',
    category: 'Luggage',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
      'https://images.unsplash.com/photo-1622560480654-d96214fdc887?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    ],
    brand: 'TravelPro',
    description: 'Water-resistant travel backpack with laptop compartment and USB charging port.',
    price: 69.99,
    listPrice: 89.99,
    stock: 35,
    vendorId,
    status: 'published',
    isActive: true,
    tags: ['featured', 'best-seller'],
    colors: ['Black', 'Navy', 'Gray'],
    sizes: ['One Size'],
    avgRating: 4.7,
    numReviews: 62,
    ratingDistribution: [],
    numSales: 43,
    isPublished: true,
    reviews: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  }
];

export default mockupProducts; 